server {
    listen localhost:9090;
    host 127.0.0.1;
    client_max_body_size 10M;
    # error_page 403 www/errors/403.html;
    # error_page 404 www/errors/404.html;
    # error_page 405 www/errors/405.html;
    # error_page 500 www/errors/500.html;
    
    location / {
        methods GET POST;
        root www/html;
        index index.html;
    }
    
    location /upload {
        methods GET POST DELETE;
        root www/upload;
        upload_path www/upload;
        index index.html;
        client_max_body_size 20M;  #higher limit for upload location
        autoindex on;
    }
    
    location /api {
        methods GET POST DELETE;
        root www/api;
        index index.html;
        autoindex on;
    }
    
    location /static {
        methods GET DELETE;
        root www/static;
        autoindex on;
    }

    location /cgi-bin {
        methods GET POST;
        root www/cgi-bin;
        cgi .php /usr/bin/php-cgi; #PHP testing
        cgi .py /usr/bin/python3;
        index index.html;
        autoindex on;
    }
}